version: '3'

services:
  ubuntu:
    image: ubuntu:20.04
    container_name: ubuntu-container
    volumes:
      - ./ansible:/ansible
      - ./aws:/root/.aws
      - ./terraform:/terraform
    command: tail -f /dev/null
    tty: true
